workflows:
  android-workflow:
    name: Build and Publish Android APK
    instance_type: mac_mini_m1
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - name: Clean Gradle Wrapper
        script: |
          ./gradlew clean
      - name: Setup Gradle Wrapper Permissions
        script: |
          chmod +x ./gradlew
      - name: Setup Gradle
        script: |
          ./gradlew dependencies
      - name: Build APK
        script: |
          ./gradlew assembleRelease
      - name: Verifica APK Generati
        script: |
          echo "Verifica di tutti i file APK generati..."
          find . -name "*.apk" -print
          echo "Verifica completata."
      - name: Sposta APK per Pubblicazione
        script: |
          echo "Spostando gli APK in build/artifacts/..."
          mkdir -p build/artifacts/
          find . -name "*.apk" -exec cp {} build/artifacts/ \;
          echo "APK spostati in build/artifacts/"
      - name: Verifica APK in Artifacts
        script: |
          echo "Verifica degli APK in build/artifacts/..."
          ls -la build/artifacts/
          echo "Verifica completata."
    artifacts:
      - build/artifacts/**/*.apk
