workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17

    scripts:
      - name: Clean Gradle Wrapper
        script: |
          echo "Pulizia di Gradle Wrapper..."
          rm -f ./gradle/wrapper/gradle-wrapper.jar
          rm -rf ~/.gradle/caches/
          rm -rf ./app/build/
          echo "Pulizia completata."

      - name: Download Gradle Wrapper
        script: |
          echo "Scaricamento di Gradle Wrapper versione 7.6..."
          ./gradlew wrapper --gradle-version 7.6
          echo "Download completato."

      - name: Fix Gradle Wrapper Permissions
        script: |
          echo "Impostazione permessi per Gradle Wrapper..."
          chmod +x ./gradlew
          chmod +x ./gradle/wrapper/gradle-wrapper.jar
          echo "Permessi impostati correttamente."

      - name: Setup Gradle
        script: |
          echo "Configurazione di Gradle..."
          ./gradlew dependencies
          echo "Configurazione completata."

      - name: Build APK
        script: |
          echo "Avvio build APK..."
          ./gradlew assembleDebug
          ./gradlew assembleRelease
          echo "Build APK completata."

      - name: Verifica File APK Generati
        script: |
          echo "Verifica di tutti i file APK generati..."
          find $PWD -name "*.apk" -print
          echo "Verifica completata."

      - name: Comprimi APK per Pubblicazione
        script: |
          echo "Comprimo tutti gli APK per la pubblicazione..."
          mkdir -p $PWD/build/artifacts/
          find $PWD -name "*.apk" -exec zip $PWD/build/artifacts/all-apks.zip {} +
          echo "Compressione completata."

      - name: Verifica ZIP Creato
        script: |
          echo "Verifica del file ZIP creato..."
          ls -la $PWD/build/artifacts/
          echo "Verifica completata."

    artifacts:
      - build/artifacts/all-apks.zip
