workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - name: Download Gradle Wrapper
        script: |
          rm -rf ./gradle/wrapper
          mkdir -p ./gradle/wrapper
          curl -L https://services.gradle.org/distributions/gradle-7.6-bin.zip -o gradle-7.6-bin.zip
          unzip gradle-7.6-bin.zip
          mv gradle-7.6/lib/plugins/gradle-wrapper-7.6.jar ./gradle/wrapper/gradle-wrapper.jar
          chmod +x ./gradlew
          chmod -R +x ./gradle/wrapper/
          ls -la ./gradle/wrapper/
      - name: Setup Gradle
        script: |
          ./gradlew wrapper
          ./gradlew dependencies
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
