workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - name: Clean and Force Dependencies Download
        script: |
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/wrapper/
          chmod +x ./gradlew
          ./gradlew wrapper --gradle-version 7.6
          ./gradlew clean
          ./gradlew dependencies --refresh-dependencies
      - name: Build APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
