workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
  - name: Setup Gradle
    script: |
      #!/bin/sh
      chmod +x ./gradlew
      ./gradlew wrapper
      ./gradlew dependencies
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
