workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60
    environment:
      android:
        image: latest
      kotlin: 1.8.22
      java: 17
    scripts:
      - name: Setup Gradle
        script: |
          chmod +x ./gradlew
          ./gradlew dependencies
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
