workflows:
  main:
    name: Build e Pubblicazione APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
      flutter: stable
    scripts:
      - name: Clean Gradle Wrapper
        script: |
          echo "Pulizia del vecchio Gradle Wrapper..."
          ./gradlew clean
          echo "Pulizia completata."
          
      - name: Fix Gradle Wrapper Permissions
        script: |
          echo "Fix dei permessi per il Gradle Wrapper..."
          chmod +x ./gradlew
          echo "Permessi corretti."

      - name: Setup Gradle
        script: |
          echo "Setup di Gradle..."
          ./gradlew --version
          echo "Setup completato."

      - name: Build APK
        script: |
          echo "Avvio build APK..."
          ./gradlew assembleRelease
          echo "Build APK completata."

      - name: Verifica APK Generati
        script: |
          echo "Verifica dettagliata di tutti i file APK generati..."
          find . -name "*.apk" -print
          echo "Verifica completata."
          
      - name: Sposta APK per Pubblicazione
        script: |
          echo "Sposto tutti gli APK per la pubblicazione..."
          mkdir -p build/artifacts/
          find . -name "*.apk" -exec cp {} build/artifacts/ \;
          echo "APK spostati in build/artifacts/"

    artifacts:
      - build/artifacts/*.apk
