workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
        
    scripts:
      - name: Clean Gradle Wrapper
        script: |
          echo "Cleaning old Gradle wrapper..."
          rm -f ./gradle/wrapper/gradle-wrapper.jar
          rm -rf ./gradle/caches/
          rm -rf ./app/build/
          echo "Pulizia completata."

      - name: Download Gradle Wrapper
        script: |
          echo "Scaricamento di Gradle wrapper versione 7.6..."
          ./gradlew wrapper --gradle-version 7.6
          echo "Download completato."
        
      - name: Fix Permissions
        script: |
          echo "Impostazione permessi..."
          chmod +x ./gradlew
          chmod +x ./gradle/wrapper/gradle-wrapper.jar
          echo "Permessi impostati correttamente."
        
      - name: Setup Gradle
        script: |
          echo "Configurazione di Gradle..."
          ./gradlew dependencies
          echo "Configurazione completata."

      - name: Build APK (Debug e Release)
        script: |
          echo "Avvio build APK Debug..."
          ./gradlew assembleDebug || echo "Debug APK build failed."
          echo "Avvio build APK Release..."
          ./gradlew assembleRelease || echo "Release APK build failed."
          echo "Build APK completata."

      - name: Verifica Output Debug
        script: |
          echo "Verifica APK Debug..."
          ls -l ./app/build/outputs/apk/debug/ || echo "No debug APK found"
        
      - name: Verifica Output Release
        script: |
          echo "Verifica APK Release..."
          ls -l ./app/build/outputs/apk/release/ || echo "No release APK found"

      - name: List All APKs
        script: |
          echo "Listing all APKs in project..."
          find . -name "*.apk" || echo "No APKs found"

    artifacts:
      - "app/build/outputs/apk/debug/*.apk"
      - "app/build/outputs/apk/release/*.apk"
