workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
        
    scripts:
      - name: Clean Gradle Wrapper
        script: |
          echo "Cleaning old Gradle wrapper..."
          rm -f ./gradle/wrapper/gradle-wrapper.jar
          rm -rf ~/.gradle/caches/
          echo "Pulizia completata."

      - name: Download Gradle Wrapper
        script: |
          echo "Scaricamento di Gradle wrapper versione 7.6..."
          ./gradlew wrapper --gradle-version 7.6
          echo "Download completato."
        
      - name: Fix Gradle Wrapper Permissions
        script: |
          echo "Impostazione permessi per Gradle Wrapper..."
          chmod +x ./gradlew
          chmod +x ./gradle/wrapper/gradle-wrapper.jar
          echo "Permessi impostati correttamente."
        
      - name: Setup Gradle
        script: |
          echo "Configurazione di Gradle..."
          ./gradlew dependencies
          echo "Configurazione completata."

      - name: Clean and Rebuild APK
        script: |
          echo "Pulizia e ricostruzione dell'APK..."
          ./gradlew clean
          ./gradlew assembleDebug
          ./gradlew assembleRelease
          echo "Build APK completata."

    artifacts:
      - build/outputs/apk/debug/*.apk
      - build/outputs/apk/release/*.apk
