name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Clean and Download Gradle Wrapper
        run: |
          rm -f ./gradle/wrapper/gradle-wrapper.jar
          ./gradlew wrapper --gradle-version 8.0
          chmod +x ./gradlew
          chmod +x ./gradle/wrapper/gradle-wrapper.jar

      - name: Build Release APK
        run: |
          ./gradlew clean assembleRelease

      - name: Verifica Output APK
        run: |
          echo "Verifica del contenuto della directory di output:"
          find . -type f
          ls -R app/build/outputs/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
